name: flutter_toolkit

packages:
  - packages/**
  - examples/**
  - scripts/**

sdkPath: '.fvm/flutter_sdk'

command:
  clean:
    hooks:
      post: melos exec --flutter -- "flutter clean"
  bootstrap:
    environment:
      sdk: ^3.7.0

scripts:
  test: melos exec --flutter -- "flutter test" && melos exec --dir-exists="bin" -- "dart test"
  format: dart format .
  outdated: melos exec "dart pub outdated"
  upgrade: melos exec "dart pub upgrade --major-versions"
  fix: melos exec "dart fix --apply"
  analyze:
    # Set concurrency to 1 to avoid crashes on low-spec machines like GitHub Actions.
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
  # run build_runner
  rb: melos exec --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
  # watch build_runner
  wb: melos exec --flutter -- "flutter pub run build_runner watch --delete-conflicting-outputs"