name: adaptive_image
description: adaptive_image用Flutterパッケージ
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
