name: mobile
description: "Example of Flutter app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  adaptive_image:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter



dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/